services:
  auth-service:
    build:
      context: ./PortalCommunityServer
      dockerfile: AuthService/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - "5001"  # חשיפת הפורט גם בתוך הקונטיינר
  courses-service:
    build:
      context: ./PortalCommunityServer
      dockerfile: CoursesService/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - "5003"  # חשיפת הפורט גם בתוך הקונטיינר

  library-service:
    build:
      context: ./PortalCommunityServer
      dockerfile: LibraryService/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - "5002"  # חשיפת הפורט גם בתוך הקונטיינר

  client:
    build:
      context: ./PortalCommunityClient
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_AUTH_SERVICE_URL=http://localhost:5001
      - NEXT_PUBLIC_LIBRARY_SERVICE_URL=http://localhost:5002
      - NEXT_PUBLIC_COURSES_SERVICE_URL=http://localhost:5003
    depends_on:
      - auth-service
      - library-service
      - courses-service